### ISSUE TITLE
O enunciado da T1Q01 não está claro

### ISSUE THREAD

**Issue by ze-gois** [rafaeldimap/DIM0141#1]
> q01.py: dado um inteiro n, gere uma sequência de inteiros seguindo a seguinte regra: se n for par, divida-o por 2 e se for ímpar, multiplique-o por 3 e some 1. Adicione os números dessa sequência na lista seq. Por exemplo, caso o inteiro passado como argumento for 22, será escrita na tela a lista: [22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1].
> 
> entrada: um inteiro n como argumnto da linha de comando (use sys.argv)
> saída: a sequência de números gerados escrita na tela

Pelo que deduzi o enunciado parece com o seguinte:

Dado um inteirio n_0 valendo n gere a seguinte sequência:

caso n_i for par
n_{i+1} = n_i/2

caso n_i for impar
n_{i+1} = n_i*3 + 1

caso n_i for 1
encerre a sequência

**Comment by ze-gois** [comment]
Fiquei com dúvida no caso que N iniciar com 0.

**Comment by rafaelbesg** [comment]
Olá @jhenriquetdg , pode assumir que é um inteiro positivo, n > 0.
